// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzhrxohknejzjwvbvckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6aHJ4b2hrbmVqemp3dmJ2Y2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1MDMzNDAsImV4cCI6MjA5NzA3OTM0MH0.5zLokTDttXyq4RBrEgOuKrKRb8qBz5FosjAdvKrCw18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});